import type { Product } from "@/lib/products";

/**
 * Collection rentrée scolaire : les 100 références de fournitures qui
 * tournent le plus en France (écriture, papeterie, classement, géométrie,
 * arts plastiques, sacs et vie scolaire).
 *
 * Prix : coût de revient de la référence + 35 % de marge.
 *
 * ⚠️ Photos : ce fichier réutilise les visuels d'illustration déjà présents
 * dans le dépôt, faute de photos produit. À remplacer par les visuels du
 * fournisseur avant mise en vente — et impérativement avant toute
 * publication sur Amazon, qui exige la photo du produit réellement vendu.
 */
export const produitsScolaires: Product[] = [
  {
    slug: "stylos-bille-bleu-lot-20",
    name: "Stylos bille bleus (lot de 20)",
    price: 12.90,
    tagline: "La réserve de l'année en une seule commande",
    description:
      "Lot de 20 stylos bille à encre bleue, pointe moyenne 1 mm. Encre fluide qui ne bave pas et capuchon ventilé conforme aux normes de sécurité scolaires.",
    specs: [
      { label: "Contenu", value: "20 stylos" },
      { label: "Pointe", value: "Moyenne, 1 mm" },
      { label: "Encre", value: "Bleue, à base d'huile" },
      { label: "Sécurité", value: "Capuchon ventilé" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "stylos-bille-4-couleurs-lot-3",
    name: "Stylos 4 couleurs (lot de 3)",
    price: 16.90,
    tagline: "Quatre encres, un seul stylo",
    description:
      "Stylo bille rétractable à 4 couleurs (bleu, noir, rouge, vert), corps caoutchouté antidérapant. L'indispensable de la prise de notes en couleur.",
    specs: [
      { label: "Contenu", value: "3 stylos" },
      { label: "Couleurs", value: "Bleu, noir, rouge, vert" },
      { label: "Pointe", value: "Moyenne, 1 mm" },
      { label: "Prise en main", value: "Zone caoutchoutée" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "stylo-plume-scolaire-cartouches",
    name: "Stylo plume scolaire + 6 cartouches",
    price: 17.90,
    tagline: "L'apprentissage de l'écriture, sans accroc",
    description:
      "Stylo plume à plume iridium pour droitiers et gauchers, grip ergonomique guidant les doigts. Livré avec 6 cartouches d'encre bleue effaçable.",
    specs: [
      { label: "Plume", value: "Iridium, medium" },
      { label: "Grip", value: "Ergonomique, droitier et gaucher" },
      { label: "Livré avec", value: "6 cartouches bleues" },
      { label: "Encre", value: "Effaçable" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "cartouches-encre-bleue-lot-50",
    name: "Cartouches d'encre bleue effaçable (lot de 50)",
    price: 10.90,
    tagline: "De quoi tenir toute l'année",
    description:
      "Boîte de 50 cartouches courtes standard, encre bleue effaçable compatible avec la majorité des stylos plume scolaires.",
    specs: [
      { label: "Contenu", value: "50 cartouches" },
      { label: "Format", value: "Courte, standard international" },
      { label: "Encre", value: "Bleue effaçable" },
      { label: "Compatibilité", value: "Stylos plume standard" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "effaceurs-reecriveurs-lot-4",
    name: "Effaceurs réécriveurs (lot de 4)",
    price: 8.90,
    tagline: "Efface d'un côté, réécrit de l'autre",
    description:
      "Effaceurs double embout : une pointe pour effacer l'encre bleue effaçable, une pointe fine bleue pour réécrire immédiatement par-dessus.",
    specs: [
      { label: "Contenu", value: "4 effaceurs" },
      { label: "Embouts", value: "Effaceur + pointe de réécriture" },
      { label: "Usage", value: "Encres bleues effaçables" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "stylos-roller-effacables-lot-6",
    name: "Stylos roller effaçables (lot de 6)",
    price: 18.90,
    tagline: "Une erreur ? Un coup de gomme et c'est réglé",
    description:
      "Rollers à encre thermosensible effaçable par friction : la gomme en bout de stylo fait disparaître le trait sans laisser de trace ni abîmer le papier.",
    specs: [
      { label: "Contenu", value: "6 rollers" },
      { label: "Pointe", value: "0,7 mm" },
      { label: "Encre", value: "Thermosensible, effaçable par friction" },
      { label: "Rechargeable", value: "Oui" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "recharges-roller-effacable-lot-12",
    name: "Recharges pour roller effaçable (lot de 12)",
    price: 12.90,
    tagline: "On garde le stylo, on change la cartouche",
    description:
      "Lot de 12 recharges 0,7 mm pour rollers effaçables : moins cher et moins de plastique que de racheter des stylos entiers.",
    specs: [
      { label: "Contenu", value: "12 recharges" },
      { label: "Pointe", value: "0,7 mm" },
      { label: "Compatibilité", value: "Rollers effaçables standard" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "crayons-papier-hb-lot-12",
    name: "Crayons à papier HB (lot de 12)",
    price: 9.90,
    tagline: "Mine tendre qui ne casse pas",
    description:
      "Douze crayons graphite HB en bois certifié, mine collée sur toute la longueur pour résister aux chutes et au taille-crayon.",
    specs: [
      { label: "Contenu", value: "12 crayons" },
      { label: "Dureté", value: "HB" },
      { label: "Bois", value: "Certifié, facile à tailler" },
      { label: "Mine", value: "Collée, anti-casse" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "portemines-05mm-lot-3",
    name: "Porte-mines 0,5 mm (lot de 3)",
    price: 12.90,
    tagline: "Un trait toujours net, sans taille-crayon",
    description:
      "Porte-mines à poussoir avec grip caoutchouté et gomme intégrée sous le capuchon. Trait constant de 0,5 mm, idéal pour la géométrie et les schémas.",
    specs: [
      { label: "Contenu", value: "3 porte-mines" },
      { label: "Mine", value: "0,5 mm" },
      { label: "Gomme", value: "Intégrée sous le capuchon" },
      { label: "Grip", value: "Caoutchouté" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "mines-05mm-hb-3-etuis",
    name: "Mines 0,5 mm HB (3 étuis)",
    price: 6.90,
    tagline: "La recharge qui manque toujours",
    description:
      "Trois étuis de mines HB 0,5 mm, 12 mines par étui, résistantes à la pression pour limiter la casse en cours d'écriture.",
    specs: [
      { label: "Contenu", value: "3 étuis de 12 mines" },
      { label: "Diamètre", value: "0,5 mm" },
      { label: "Dureté", value: "HB" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "gommes-blanches-lot-4",
    name: "Gommes blanches sans PVC (lot de 4)",
    price: 6.90,
    tagline: "Efface net, sans trace grise",
    description:
      "Gommes en matière synthétique sans PVC ni phtalates, qui effacent le graphite sans laisser de résidu gras ni abîmer la feuille.",
    specs: [
      { label: "Contenu", value: "4 gommes" },
      { label: "Matière", value: "Synthétique sans PVC" },
      { label: "Usage", value: "Graphite et crayon de couleur clair" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "taille-crayon-reservoir-2-trous",
    name: "Taille-crayon à réservoir 2 trous",
    price: 5.90,
    tagline: "Zéro copeau sur la table",
    description:
      "Taille-crayon deux diamètres (crayons standard et crayons de couleur épais) avec réservoir transparent à couvercle verrouillable.",
    specs: [
      { label: "Trous", value: "2 diamètres : 8 mm et 11 mm" },
      { label: "Réservoir", value: "Transparent, verrouillable" },
      { label: "Lames", value: "Acier trempé" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "stylos-bille-pointe-fine-lot-10",
    name: "Stylos bille pointe fine 0,7 mm (lot de 10)",
    price: 10.90,
    tagline: "Pour les écritures serrées",
    description:
      "Dix stylos bille à pointe fine 0,7 mm : trait précis pour les annotations, les marges et les cahiers à petits carreaux.",
    specs: [
      { label: "Contenu", value: "10 stylos" },
      { label: "Pointe", value: "Fine, 0,7 mm" },
      { label: "Encre", value: "Bleue" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "feutres-pointe-fine-lot-12",
    name: "Feutres pointe fine 0,4 mm (lot de 12)",
    price: 17.90,
    tagline: "Douze couleurs pour des fiches lisibles",
    description:
      "Feutres à pointe fine 0,4 mm sous protection métal, encre à base d'eau qui ne traverse pas le papier. Parfaits pour les fiches de révision et le bullet journal.",
    specs: [
      { label: "Contenu", value: "12 feutres" },
      { label: "Pointe", value: "0,4 mm, protégée métal" },
      { label: "Encre", value: "À base d'eau" },
      { label: "Traverse le papier", value: "Non" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "marqueurs-permanents-lot-4",
    name: "Marqueurs permanents (lot de 4)",
    price: 12.90,
    tagline: "Écrit sur presque tout, résiste à l'eau",
    description:
      "Quatre marqueurs indélébiles à pointe ogive, encre à séchage rapide résistante à l'eau, qui marque le carton, le plastique, le métal et le verre.",
    specs: [
      { label: "Contenu", value: "4 marqueurs" },
      { label: "Pointe", value: "Ogive, 1 à 3 mm" },
      { label: "Encre", value: "Permanente, résistante à l'eau" },
      { label: "Supports", value: "Carton, plastique, métal, verre" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "marqueurs-ardoise-lot-4",
    name: "Marqueurs pour ardoise blanche (lot de 4)",
    price: 10.90,
    tagline: "S'efface d'un simple coup de chiffon",
    description:
      "Marqueurs effaçables à sec pour ardoise et tableau blanc, encre sans solvant agressif et faiblement odorante.",
    specs: [
      { label: "Contenu", value: "4 marqueurs" },
      { label: "Pointe", value: "Ogive, 2 mm" },
      { label: "Encre", value: "Effaçable à sec, peu odorante" },
      { label: "Supports", value: "Ardoise blanche, tableau" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "correcteurs-souris-lot-2",
    name: "Correcteurs souris 5 m (lot de 2)",
    price: 9.90,
    tagline: "Correction sèche, réécriture immédiate",
    description:
      "Deux souris correctrices à ruban 5 m x 5 mm : la correction est sèche, on peut réécrire par-dessus sans attendre et sans pâte qui craquelle.",
    specs: [
      { label: "Contenu", value: "2 correcteurs" },
      { label: "Ruban", value: "5 m x 5 mm" },
      { label: "Séchage", value: "Immédiat" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "blanc-correcteur-flacon-lot-2",
    name: "Blanc correcteur flacon (lot de 2)",
    price: 7.90,
    tagline: "Le classique, avec pinceau de précision",
    description:
      "Deux flacons de 20 ml de correcteur liquide à pinceau, formule à séchage rapide et bonne opacité en une seule couche.",
    specs: [
      { label: "Contenu", value: "2 flacons de 20 ml" },
      { label: "Applicateur", value: "Pinceau" },
      { label: "Séchage", value: "Rapide" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "stylos-gel-noirs-lot-12",
    name: "Stylos gel noirs 0,5 mm (lot de 12)",
    price: 16.90,
    tagline: "Le noir profond des copies au propre",
    description:
      "Douze stylos à encre gel noire 0,5 mm, écriture fluide sans à-coups et rendu très contrasté pour les copies rendues.",
    specs: [
      { label: "Contenu", value: "12 stylos" },
      { label: "Pointe", value: "0,5 mm" },
      { label: "Encre", value: "Gel noire, séchage rapide" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "parure-stylo-bille-roller",
    name: "Parure stylo bille + roller",
    price: 33.90,
    tagline: "Le cadeau de rentrée qui fait sérieux",
    description:
      "Coffret deux pièces, stylo bille et roller en métal laqué avec attache clip, livré dans un écrin. Recharges standard faciles à trouver.",
    specs: [
      { label: "Contenu", value: "1 stylo bille + 1 roller" },
      { label: "Matière", value: "Métal laqué" },
      { label: "Livré avec", value: "Écrin cadeau" },
      { label: "Recharges", value: "Format standard" },
    ],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800"],
    categorie: "scolaire",
    famille: "ecriture",
    badge: "Rentrée",
  },
  {
    slug: "cahier-seyes-96p-24x32",
    name: "Cahier grands carreaux Seyès 96 pages 24x32",
    price: 5.90,
    tagline: "Le format demandé partout au collège",
    description:
      "Cahier piqué 24x32 cm, 96 pages de papier 90 g réglure Seyès, couverture polypropylène qui ne corne pas au fond du sac.",
    specs: [
      { label: "Format", value: "24 x 32 cm" },
      { label: "Pages", value: "96" },
      { label: "Réglure", value: "Seyès (grands carreaux)" },
      { label: "Papier", value: "90 g" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "cahiers-seyes-96p-lot-5",
    name: "Cahiers Seyès 96 pages 24x32 (lot de 5)",
    price: 22.90,
    tagline: "Cinq matières, cinq couleurs de couverture",
    description:
      "Lot de 5 cahiers 24x32 cm, 96 pages, papier 90 g réglure Seyès, couvertures de couleurs différentes pour repérer chaque matière d'un coup d'œil.",
    specs: [
      { label: "Contenu", value: "5 cahiers" },
      { label: "Format", value: "24 x 32 cm" },
      { label: "Pages", value: "96 par cahier" },
      { label: "Couvertures", value: "5 couleurs assorties" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "cahier-petits-carreaux-96p-24x32",
    name: "Cahier petits carreaux 5x5 96 pages 24x32",
    price: 5.90,
    tagline: "Pour les maths et les schémas",
    description:
      "Cahier piqué 24x32 cm, 96 pages 90 g à petits carreaux 5x5 mm, réglure privilégiée en mathématiques, physique et technologie.",
    specs: [
      { label: "Format", value: "24 x 32 cm" },
      { label: "Pages", value: "96" },
      { label: "Réglure", value: "Petits carreaux 5x5 mm" },
      { label: "Papier", value: "90 g" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "cahier-17x22-seyes-96p",
    name: "Cahier Seyès 96 pages 17x22",
    price: 4.90,
    tagline: "Le petit format des langues",
    description:
      "Cahier piqué 17x22 cm, 96 pages 90 g réglure Seyès. Format compact souvent demandé pour les langues vivantes et les leçons.",
    specs: [
      { label: "Format", value: "17 x 22 cm" },
      { label: "Pages", value: "96" },
      { label: "Réglure", value: "Seyès" },
      { label: "Papier", value: "90 g" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "cahier-travaux-pratiques-96p",
    name: "Cahier de travaux pratiques 96 pages",
    price: 6.90,
    tagline: "Une page unie, une page réglée",
    description:
      "Cahier TP 24x32 cm alternant page blanche pour les schémas et page Seyès pour la rédaction. Indispensable en SVT et physique-chimie.",
    specs: [
      { label: "Format", value: "24 x 32 cm" },
      { label: "Pages", value: "96" },
      { label: "Réglure", value: "Alternance uni / Seyès" },
      { label: "Usage", value: "SVT, physique-chimie" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "cahiers-brouillon-96p-lot-3",
    name: "Cahiers de brouillon 96 pages (lot de 3)",
    price: 9.90,
    tagline: "Pour chercher sans se soucier des ratures",
    description:
      "Trois cahiers de brouillon 17x22 cm, 96 pages de papier recyclé, à prix serré pour les calculs et les essais.",
    specs: [
      { label: "Contenu", value: "3 cahiers" },
      { label: "Format", value: "17 x 22 cm" },
      { label: "Pages", value: "96 par cahier" },
      { label: "Papier", value: "Recyclé" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "copies-doubles-perforees-200p",
    name: "Copies doubles perforées grands carreaux (200 pages)",
    price: 13.90,
    tagline: "Le paquet qui dure un trimestre",
    description:
      "Deux cents pages de copies doubles A4 perforées, papier 90 g réglure Seyès : le format exigé pour les devoirs surveillés.",
    specs: [
      { label: "Contenu", value: "200 pages" },
      { label: "Format", value: "A4 (21 x 29,7 cm)" },
      { label: "Réglure", value: "Seyès" },
      { label: "Perforation", value: "2 trous" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "copies-simples-perforees-200p",
    name: "Copies simples perforées grands carreaux (200 pages)",
    price: 12.90,
    tagline: "À glisser directement dans le classeur",
    description:
      "Deux cents pages simples A4 perforées 2 trous, papier 90 g réglure Seyès, prêtes à classer sans pochette.",
    specs: [
      { label: "Contenu", value: "200 pages" },
      { label: "Format", value: "A4" },
      { label: "Réglure", value: "Seyès" },
      { label: "Perforation", value: "2 trous" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "feuillets-mobiles-a4-seyes-400p",
    name: "Feuillets mobiles A4 Seyès (400 pages)",
    price: 17.90,
    tagline: "La recharge économique du classeur",
    description:
      "Sachet de 400 pages A4 perforées, papier 90 g réglure Seyès, conditionnées en paquets de 100 pour rester bien à plat.",
    specs: [
      { label: "Contenu", value: "400 pages" },
      { label: "Format", value: "A4" },
      { label: "Réglure", value: "Seyès" },
      { label: "Papier", value: "90 g" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "bloc-notes-a4-perfore-160p",
    name: "Bloc-notes A4 perforé 160 pages",
    price: 9.90,
    tagline: "On détache, on classe, on avance",
    description:
      "Bloc-notes A4 à reliure agrafée, 160 pages microperforées et prédécoupées pour se détacher sans bavure, papier 80 g.",
    specs: [
      { label: "Format", value: "A4" },
      { label: "Pages", value: "160" },
      { label: "Détachement", value: "Microperforé" },
      { label: "Perforation", value: "4 trous" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "blocs-stenos-lot-3",
    name: "Blocs sténo (lot de 3)",
    price: 8.90,
    tagline: "Le carnet qui tient dans la poche",
    description:
      "Trois blocs sténo à spirale en tête, 80 pages lignées chacun, couverture rigide pour écrire debout.",
    specs: [
      { label: "Contenu", value: "3 blocs" },
      { label: "Pages", value: "80 par bloc" },
      { label: "Réglure", value: "Lignée" },
      { label: "Reliure", value: "Spirale en tête" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "repertoire-alphabetique-96p",
    name: "Répertoire alphabétique 96 pages",
    price: 6.90,
    tagline: "Le vocabulaire, classé d'office",
    description:
      "Répertoire 11x17 cm à onglets alphabétiques découpés, 96 pages réglure Seyès. Le compagnon des cours de langues.",
    specs: [
      { label: "Format", value: "11 x 17 cm" },
      { label: "Pages", value: "96" },
      { label: "Onglets", value: "Alphabétiques découpés" },
      { label: "Usage", value: "Vocabulaire, langues" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "carnets-a5-lignes-lot-2",
    name: "Carnets A5 lignés (lot de 2)",
    price: 10.90,
    tagline: "Deux carnets souples pour tout noter",
    description:
      "Deux carnets A5 à couverture souple, 96 pages lignées, élastique de fermeture et marque-page ruban.",
    specs: [
      { label: "Contenu", value: "2 carnets" },
      { label: "Format", value: "A5" },
      { label: "Pages", value: "96 lignées" },
      { label: "Fermeture", value: "Élastique + marque-page" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "agenda-scolaire-2026-2027",
    name: "Agenda scolaire 2026-2027",
    price: 17.90,
    tagline: "Une semaine sur deux pages, d'août à juillet",
    description:
      "Agenda scolaire couvrant l'année complète, une semaine sur deux pages, avec calendrier des vacances par zone et pages de notes en fin de volume.",
    specs: [
      { label: "Période", value: "Août 2026 à juillet 2027" },
      { label: "Format", value: "1 semaine sur 2 pages" },
      { label: "Format papier", value: "12 x 17 cm" },
      { label: "Inclus", value: "Calendrier des zones A, B, C" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "cahier-de-textes",
    name: "Cahier de textes",
    price: 13.90,
    tagline: "Les devoirs, jour par jour",
    description:
      "Cahier de textes à reliure spirale, une page par jour de classe, couverture rigide plastifiée et porte-crayon élastique.",
    specs: [
      { label: "Reliure", value: "Spirale" },
      { label: "Organisation", value: "1 page par jour de classe" },
      { label: "Couverture", value: "Rigide plastifiée" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "protege-cahiers-24x32-lot-6",
    name: "Protège-cahiers 24x32 (lot de 6)",
    price: 12.90,
    tagline: "Six couleurs, six matières",
    description:
      "Six protège-cahiers 24x32 cm en polypropylène opaque avec porte-étiquette et rabats intérieurs, lavables d'un coup d'éponge.",
    specs: [
      { label: "Contenu", value: "6 protège-cahiers" },
      { label: "Format", value: "24 x 32 cm" },
      { label: "Matière", value: "Polypropylène opaque" },
      { label: "Porte-étiquette", value: "Oui" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "protege-documents-60-vues",
    name: "Protège-documents 60 vues",
    price: 12.90,
    tagline: "Trente pochettes, zéro feuille perdue",
    description:
      "Protège-documents A4 à 30 pochettes soudées (60 vues), couverture polypropylène souple et dos porte-étiquette.",
    specs: [
      { label: "Format", value: "A4" },
      { label: "Capacité", value: "60 vues (30 pochettes)" },
      { label: "Matière", value: "Polypropylène" },
      { label: "Dos", value: "Porte-étiquette" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "porte-vues-100-vues",
    name: "Porte-vues 100 vues",
    price: 17.90,
    tagline: "Pour les gros dossiers de l'année",
    description:
      "Porte-vues A4 à 50 pochettes soudées (100 vues), couverture rigide et pochette de personnalisation en première de couverture.",
    specs: [
      { label: "Format", value: "A4" },
      { label: "Capacité", value: "100 vues (50 pochettes)" },
      { label: "Couverture", value: "Rigide personnalisable" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "papier-millimetre-a4-50f",
    name: "Papier millimétré A4 (50 feuilles)",
    price: 8.90,
    tagline: "Des courbes précises au millimètre",
    description:
      "Pochette de 50 feuilles A4 de papier millimétré orange sur fond blanc, papier 90 g qui supporte le crayon et l'encre.",
    specs: [
      { label: "Contenu", value: "50 feuilles" },
      { label: "Format", value: "A4" },
      { label: "Quadrillage", value: "Millimétré" },
      { label: "Papier", value: "90 g" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "papier-calque-a4-50f",
    name: "Papier calque A4 (50 feuilles)",
    price: 9.90,
    tagline: "Pour décalquer et superposer",
    description:
      "Cinquante feuilles A4 de papier calque 90 g, translucide et suffisamment épais pour être manipulé sans se déchirer.",
    specs: [
      { label: "Contenu", value: "50 feuilles" },
      { label: "Format", value: "A4" },
      { label: "Grammage", value: "90 g" },
      { label: "Usage", value: "Dessin technique, arts plastiques" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "papier-dessin-blanc-a4-160g",
    name: "Papier dessin blanc A4 160 g (50 feuilles)",
    price: 12.90,
    tagline: "Assez épais pour la peinture",
    description:
      "Pochette de 50 feuilles A4 de papier à dessin blanc 160 g, grain fin adapté au crayon, au feutre et à la gouache légère.",
    specs: [
      { label: "Contenu", value: "50 feuilles" },
      { label: "Format", value: "A4" },
      { label: "Grammage", value: "160 g" },
      { label: "Grain", value: "Fin" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "pochette-papier-dessin-couleur-a3",
    name: "Pochette papier dessin couleur A3",
    price: 13.90,
    tagline: "Douze teintes en grand format",
    description:
      "Pochette A3 de 12 feuilles de papier à dessin 160 g en couleurs vives assorties, pour les affiches et les exposés.",
    specs: [
      { label: "Contenu", value: "12 feuilles" },
      { label: "Format", value: "A3" },
      { label: "Grammage", value: "160 g" },
      { label: "Coloris", value: "12 couleurs assorties" },
    ],
    images: ["https://images.unsplash.com/photo-1568205612837-017257d2310a?w=800"],
    categorie: "scolaire",
    famille: "papier",
    badge: "Rentrée",
  },
  {
    slug: "classeur-a4-souple-dos-40",
    name: "Classeur A4 souple dos 40 mm",
    price: 6.90,
    tagline: "Léger, il ne plombe pas le sac",
    description:
      "Classeur A4 en polypropylène souple, dos de 40 mm, mécanisme 4 anneaux en O et porte-étiquette au dos.",
    specs: [
      { label: "Format", value: "A4" },
      { label: "Dos", value: "40 mm" },
      { label: "Mécanisme", value: "4 anneaux en O" },
      { label: "Matière", value: "Polypropylène souple" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "classeur-a4-rigide-dos-70",
    name: "Classeur A4 rigide dos 70 mm",
    price: 12.90,
    tagline: "Le classeur d'archivage de l'année",
    description:
      "Classeur A4 à couverture rigide recouverte de polypropylène, dos de 70 mm, mécanisme 4 anneaux en D pour des pages toujours à plat.",
    specs: [
      { label: "Format", value: "A4" },
      { label: "Dos", value: "70 mm" },
      { label: "Mécanisme", value: "4 anneaux en D" },
      { label: "Couverture", value: "Rigide plastifiée" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "classeurs-souples-lot-4",
    name: "Classeurs A4 souples (lot de 4)",
    price: 21.90,
    tagline: "Un classeur par matière principale",
    description:
      "Lot de 4 classeurs A4 souples dos 40 mm, coloris assortis, mécanisme 4 anneaux et porte-étiquette.",
    specs: [
      { label: "Contenu", value: "4 classeurs" },
      { label: "Format", value: "A4" },
      { label: "Dos", value: "40 mm" },
      { label: "Coloris", value: "4 couleurs assorties" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "intercalaires-carton-12-positions",
    name: "Intercalaires carton 12 positions",
    price: 6.90,
    tagline: "Douze onglets pour s'y retrouver",
    description:
      "Jeu de 12 intercalaires A4 en carte forte 170 g, onglets de couleurs différentes et page de sommaire à remplir.",
    specs: [
      { label: "Contenu", value: "12 intercalaires" },
      { label: "Format", value: "A4" },
      { label: "Matière", value: "Carte 170 g" },
      { label: "Inclus", value: "Page de sommaire" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "pochettes-perforees-a4-lot-100",
    name: "Pochettes perforées A4 (lot de 100)",
    price: 10.90,
    tagline: "Cent pochettes transparentes, ouverture en haut",
    description:
      "Boîte de 100 pochettes A4 perforées 11 trous en polypropylène lisse 5/100, ouverture sur le côté long.",
    specs: [
      { label: "Contenu", value: "100 pochettes" },
      { label: "Format", value: "A4" },
      { label: "Perforation", value: "11 trous" },
      { label: "Épaisseur", value: "5/100" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "chemises-elastique-3-rabats-lot-6",
    name: "Chemises à élastique 3 rabats (lot de 6)",
    price: 16.90,
    tagline: "Rien ne dépasse, rien ne s'échappe",
    description:
      "Six chemises A4 à trois rabats et élastiques croisés, en carte lustrée, capacité d'environ 200 feuilles chacune.",
    specs: [
      { label: "Contenu", value: "6 chemises" },
      { label: "Format", value: "A4" },
      { label: "Fermeture", value: "Élastiques croisés" },
      { label: "Capacité", value: "≈ 200 feuilles" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "trieur-8-compartiments",
    name: "Trieur 8 compartiments",
    price: 13.90,
    tagline: "Le tri du jour, en une seule main",
    description:
      "Trieur A4 à 8 compartiments à soufflets, fermeture par rabat élastique, onglets repositionnables à personnaliser.",
    specs: [
      { label: "Format", value: "A4" },
      { label: "Compartiments", value: "8" },
      { label: "Fermeture", value: "Rabat élastique" },
      { label: "Onglets", value: "Personnalisables" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "trieur-12-compartiments",
    name: "Trieur 12 compartiments",
    price: 17.90,
    tagline: "Une case par matière",
    description:
      "Trieur A4 à 12 compartiments à soufflets renforcés, dos extensible et fermeture élastique, pour couvrir toutes les matières de l'emploi du temps.",
    specs: [
      { label: "Format", value: "A4" },
      { label: "Compartiments", value: "12" },
      { label: "Dos", value: "Extensible" },
      { label: "Fermeture", value: "Élastique" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "boites-archives-a4-lot-3",
    name: "Boîtes d'archives A4 (lot de 3)",
    price: 17.90,
    tagline: "L'année dernière, rangée proprement",
    description:
      "Trois boîtes d'archives A4 en carton recyclé à montage rapide, dos de 100 mm et zone d'inscription sur la tranche.",
    specs: [
      { label: "Contenu", value: "3 boîtes" },
      { label: "Format", value: "A4" },
      { label: "Dos", value: "100 mm" },
      { label: "Matière", value: "Carton recyclé" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "chemises-cartonnees-lot-50",
    name: "Chemises cartonnées (lot de 50)",
    price: 13.90,
    tagline: "Le classement en vrac, en mieux",
    description:
      "Cinquante chemises A4 en carte recyclée 220 g, coloris assortis, pour regrouper les documents par thème.",
    specs: [
      { label: "Contenu", value: "50 chemises" },
      { label: "Format", value: "A4" },
      { label: "Grammage", value: "220 g" },
      { label: "Matière", value: "Carte recyclée" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "porte-documents-zippe-a4",
    name: "Porte-documents zippé A4",
    price: 16.90,
    tagline: "Le dossier qui voyage sans se froisser",
    description:
      "Porte-documents A4 en polypropylène rigide à fermeture éclair sur trois côtés, avec poche intérieure et passant.",
    specs: [
      { label: "Format", value: "A4" },
      { label: "Fermeture", value: "Éclair 3 côtés" },
      { label: "Matière", value: "Polypropylène rigide" },
      { label: "Poche", value: "Intérieure" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "sous-main-bureau-transparent",
    name: "Sous-main de bureau transparent",
    price: 17.90,
    tagline: "L'emploi du temps toujours sous les yeux",
    description:
      "Sous-main 40x53 cm à rabat transparent permettant de glisser emploi du temps, photos ou antisèches de conjugaison. Base souple antidérapante.",
    specs: [
      { label: "Dimensions", value: "40 x 53 cm" },
      { label: "Rabat", value: "Transparent" },
      { label: "Base", value: "Antidérapante" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "classement",
    badge: "Rentrée",
  },
  {
    slug: "kit-geometrie-4-pieces",
    name: "Kit de géométrie 4 pièces",
    price: 10.90,
    tagline: "Règle, équerre, rapporteur : tout y est",
    description:
      "Kit complet en plastique incassable : règle 20 cm, équerre 60°, équerre 45° et rapporteur 180°, livrés dans une pochette.",
    specs: [
      { label: "Contenu", value: "Règle, 2 équerres, rapporteur" },
      { label: "Matière", value: "Plastique incassable" },
      { label: "Graduation", value: "Lisible, non effaçable" },
      { label: "Livré avec", value: "Pochette de rangement" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "geometrie",
    badge: "Rentrée",
  },
  {
    slug: "regle-plate-30cm",
    name: "Règle plate 30 cm",
    price: 4.90,
    tagline: "Trente centimètres qui ne se voilent pas",
    description:
      "Règle plate de 30 cm en plastique rigide, graduation gravée qui ne s'efface pas au frottement, bord droit sans bavure.",
    specs: [
      { label: "Longueur", value: "30 cm" },
      { label: "Matière", value: "Plastique rigide" },
      { label: "Graduation", value: "Gravée" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "geometrie",
    badge: "Rentrée",
  },
  {
    slug: "equerre-60-21cm",
    name: "Équerre 60° 21 cm",
    price: 4.90,
    tagline: "L'angle juste, à chaque tracé",
    description:
      "Équerre 60° à hypoténuse de 21 cm, plastique transparent gradué permettant de voir le tracé au travers.",
    specs: [
      { label: "Angle", value: "60°" },
      { label: "Hypoténuse", value: "21 cm" },
      { label: "Matière", value: "Plastique transparent" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "geometrie",
    badge: "Rentrée",
  },
  {
    slug: "rapporteur-180",
    name: "Rapporteur 180°",
    price: 4.90,
    tagline: "Double graduation, lecture immédiate",
    description:
      "Rapporteur demi-circulaire 180° à double graduation en degrés, plastique transparent avec repère central marqué.",
    specs: [
      { label: "Amplitude", value: "180°" },
      { label: "Graduation", value: "Double, en degrés" },
      { label: "Matière", value: "Plastique transparent" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "geometrie",
    badge: "Rentrée",
  },
  {
    slug: "compas-scolaire-etui",
    name: "Compas scolaire avec étui",
    price: 13.90,
    tagline: "Des cercles nets, sans dérapage",
    description:
      "Compas en métal à branches réglables et molette de blocage, livré avec mine de rechange et étui rigide.",
    specs: [
      { label: "Matière", value: "Métal" },
      { label: "Blocage", value: "Molette" },
      { label: "Livré avec", value: "Mine de rechange et étui" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "geometrie",
    badge: "Rentrée",
  },
  {
    slug: "compas-porte-crayon-precision",
    name: "Compas de précision porte-crayon",
    price: 20.90,
    tagline: "Il accepte n'importe quel crayon",
    description:
      "Compas à porte-crayon universel et réglage micrométrique par molette centrale, pour des cercles précis jusqu'à 30 cm de diamètre.",
    specs: [
      { label: "Réglage", value: "Micrométrique central" },
      { label: "Porte-crayon", value: "Universel" },
      { label: "Diamètre max", value: "30 cm" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "geometrie",
    badge: "Rentrée",
  },
  {
    slug: "calculatrice-scientifique-college",
    name: "Calculatrice scientifique collège",
    price: 33.90,
    tagline: "Le modèle autorisé aux examens",
    description:
      "Calculatrice scientifique avec écran 2 lignes, plus de 250 fonctions, mode fraction, statistiques et trigonométrie. Coque de protection incluse.",
    specs: [
      { label: "Écran", value: "2 lignes" },
      { label: "Fonctions", value: "250+" },
      { label: "Modes", value: "Fractions, statistiques, trigonométrie" },
      { label: "Alimentation", value: "Pile, avec coque de protection" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "geometrie",
    badge: "Rentrée",
  },
  {
    slug: "calculatrice-graphique-lycee",
    name: "Calculatrice graphique lycée",
    price: 107.90,
    tagline: "Courbes, tableaux et programmes",
    description:
      "Calculatrice graphique à écran haute résolution, tracé de courbes, tableaux de valeurs, statistiques et mode examen conforme aux épreuves du baccalauréat.",
    specs: [
      { label: "Écran", value: "Haute résolution rétroéclairé" },
      { label: "Fonctions", value: "Courbes, tableaux, statistiques" },
      { label: "Mode examen", value: "Oui" },
      { label: "Alimentation", value: "Batterie rechargeable USB" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "geometrie",
    badge: "Rentrée",
  },
  {
    slug: "calculatrice-basique-bureau",
    name: "Calculatrice de bureau 12 chiffres",
    price: 17.90,
    tagline: "Grandes touches, grand écran",
    description:
      "Calculatrice de bureau à écran incliné 12 chiffres, touches larges, double alimentation solaire et pile, avec calcul de TVA et de pourcentages.",
    specs: [
      { label: "Écran", value: "12 chiffres, incliné" },
      { label: "Alimentation", value: "Solaire + pile" },
      { label: "Fonctions", value: "TVA, pourcentages, mémoire" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "geometrie",
    badge: "Rentrée",
  },
  {
    slug: "regle-metallique-50cm",
    name: "Règle métallique 50 cm",
    price: 12.90,
    tagline: "Elle survivra à toute la scolarité",
    description:
      "Règle en aluminium anodisé de 50 cm à dos antidérapant, graduation gravée indélébile, également utilisable comme guide de coupe.",
    specs: [
      { label: "Longueur", value: "50 cm" },
      { label: "Matière", value: "Aluminium anodisé" },
      { label: "Dos", value: "Antidérapant" },
      { label: "Graduation", value: "Gravée" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "geometrie",
    badge: "Rentrée",
  },
  {
    slug: "ciseaux-scolaires-bouts-ronds-13cm",
    name: "Ciseaux scolaires bouts ronds 13 cm",
    price: 6.90,
    tagline: "Coupe franche, bouts sécurisés",
    description:
      "Ciseaux de 13 cm à lames inox et bouts arrondis, anneaux souples adaptés aux droitiers comme aux gauchers.",
    specs: [
      { label: "Longueur", value: "13 cm" },
      { label: "Lames", value: "Inox, bouts ronds" },
      { label: "Prise", value: "Droitier et gaucher" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "ciseaux-bureau-21cm",
    name: "Ciseaux de bureau 21 cm",
    price: 10.90,
    tagline: "Pour le carton et les gros travaux",
    description:
      "Ciseaux de 21 cm à lames inox affûtées et poignées ergonomiques bi-matière, adaptés au papier épais et au carton fin.",
    specs: [
      { label: "Longueur", value: "21 cm" },
      { label: "Lames", value: "Inox affûté" },
      { label: "Poignées", value: "Ergonomiques bi-matière" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "colle-baton-21g-lot-6",
    name: "Colles bâton 21 g (lot de 6)",
    price: 13.90,
    tagline: "Colle blanche qui devient invisible",
    description:
      "Six bâtons de colle de 21 g, formule lavable sans solvant, blanche à l'application puis transparente en séchant.",
    specs: [
      { label: "Contenu", value: "6 bâtons de 21 g" },
      { label: "Formule", value: "Sans solvant, lavable" },
      { label: "Séchage", value: "Transparent" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "colle-liquide-blanche-250ml",
    name: "Colle liquide blanche 250 ml",
    price: 8.90,
    tagline: "Le flacon des travaux manuels",
    description:
      "Flacon de 250 ml de colle vinylique blanche à embout applicateur, pour le papier, le carton, le bois léger et le tissu.",
    specs: [
      { label: "Contenance", value: "250 ml" },
      { label: "Type", value: "Colle vinylique" },
      { label: "Supports", value: "Papier, carton, bois léger, tissu" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "ruban-adhesif-invisible-lot-8",
    name: "Ruban adhésif invisible (lot de 8)",
    price: 12.90,
    tagline: "Invisible une fois posé, et il s'écrit dessus",
    description:
      "Huit rouleaux de ruban adhésif mat 19 mm x 33 m, invisible après application et inscriptible au stylo.",
    specs: [
      { label: "Contenu", value: "8 rouleaux" },
      { label: "Dimensions", value: "19 mm x 33 m" },
      { label: "Finition", value: "Mat, invisible" },
      { label: "Inscriptible", value: "Oui" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "devidoir-bureau-ruban",
    name: "Dévidoir de bureau lesté",
    price: 10.90,
    tagline: "On tire d'une main, il ne bouge pas",
    description:
      "Dévidoir de bureau lesté à base antidérapante et lame de coupe métal, compatible avec les rouleaux 19 mm x 33 m.",
    specs: [
      { label: "Compatibilité", value: "Rouleaux 19 mm x 33 m" },
      { label: "Base", value: "Lestée, antidérapante" },
      { label: "Lame", value: "Métal" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "agrafeuse-metal-24-6",
    name: "Agrafeuse métal 24/6",
    price: 16.90,
    tagline: "Vingt feuilles d'un seul geste",
    description:
      "Agrafeuse demi-format à corps métal, capacité 20 feuilles, agrafes 24/6 et 26/6, avec fonction ouverture pour agrafage mural.",
    specs: [
      { label: "Capacité", value: "20 feuilles" },
      { label: "Agrafes", value: "24/6 et 26/6" },
      { label: "Corps", value: "Métal" },
      { label: "Fonction", value: "Agrafage à plat et mural" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "agrafes-24-6-boite-5000",
    name: "Agrafes 24/6 (boîte de 5000)",
    price: 8.90,
    tagline: "La recharge qu'on oublie toujours",
    description:
      "Boîte de 5000 agrafes galvanisées 24/6, compatibles avec la grande majorité des agrafeuses de bureau.",
    specs: [
      { label: "Contenu", value: "5000 agrafes" },
      { label: "Format", value: "24/6" },
      { label: "Finition", value: "Galvanisée" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "perforateur-2-trous-25f",
    name: "Perforateur 2 trous 25 feuilles",
    price: 17.90,
    tagline: "Des trous nets, toujours alignés",
    description:
      "Perforateur métal 2 trous d'une capacité de 25 feuilles, guide de format réglable (A4, A5, US) et récupérateur de confettis.",
    specs: [
      { label: "Capacité", value: "25 feuilles" },
      { label: "Trous", value: "2, écartement 80 mm" },
      { label: "Guide", value: "A4, A5, US" },
      { label: "Corps", value: "Métal" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "trombones-33mm-boite-500",
    name: "Trombones 33 mm (boîte de 500)",
    price: 6.90,
    tagline: "Cinq cents, de quoi voir venir",
    description:
      "Boîte de 500 trombones galvanisés de 33 mm, ressort suffisant pour tenir une vingtaine de feuilles sans marquer le papier.",
    specs: [
      { label: "Contenu", value: "500 trombones" },
      { label: "Longueur", value: "33 mm" },
      { label: "Finition", value: "Galvanisée" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "punaises-couleur-boite-100",
    name: "Punaises de couleur (boîte de 100)",
    price: 5.90,
    tagline: "Pour le tableau de liège au-dessus du bureau",
    description:
      "Boîte de 100 punaises à tête plastique de couleurs assorties, pointe acier, adaptées au liège et aux panneaux d'affichage.",
    specs: [
      { label: "Contenu", value: "100 punaises" },
      { label: "Tête", value: "Plastique, coloris assortis" },
      { label: "Pointe", value: "Acier" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "pinces-double-clip-assorties-lot-40",
    name: "Pinces double clip assorties (lot de 40)",
    price: 12.90,
    tagline: "Trois tailles pour tous les paquets",
    description:
      "Quarante pinces double clip en acier laqué noir réparties en trois tailles (19, 25 et 32 mm), anses rabattables.",
    specs: [
      { label: "Contenu", value: "40 pinces" },
      { label: "Tailles", value: "19, 25 et 32 mm" },
      { label: "Matière", value: "Acier laqué" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "elastiques-bureau-100g",
    name: "Élastiques de bureau (sachet 100 g)",
    price: 6.90,
    tagline: "Le vrac utile",
    description:
      "Sachet de 100 g d'élastiques en caoutchouc naturel de tailles assorties, souples et résistants au vieillissement.",
    specs: [
      { label: "Poids", value: "100 g" },
      { label: "Matière", value: "Caoutchouc naturel" },
      { label: "Tailles", value: "Assorties" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "cutter-lame-18mm-securite",
    name: "Cutter à lame 18 mm sécurisé",
    price: 9.90,
    tagline: "Lame verrouillable, coupe maîtrisée",
    description:
      "Cutter à lame sécable de 18 mm avec molette de blocage, corps métal renforcé et casse-lame intégré au capuchon arrière.",
    specs: [
      { label: "Lame", value: "18 mm sécable" },
      { label: "Blocage", value: "Molette de verrouillage" },
      { label: "Corps", value: "Métal renforcé" },
      { label: "Casse-lame", value: "Intégré" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "bureau",
    badge: "Rentrée",
  },
  {
    slug: "feutres-coloriage-lot-24",
    name: "Feutres de coloriage (lot de 24)",
    price: 17.90,
    tagline: "Vingt-quatre couleurs lavables",
    description:
      "Vingt-quatre feutres à pointe moyenne bloquée, encre lavable à l'eau sur la peau et sur la plupart des textiles.",
    specs: [
      { label: "Contenu", value: "24 feutres" },
      { label: "Pointe", value: "Moyenne, bloquée" },
      { label: "Encre", value: "Lavable à l'eau" },
      { label: "Capuchon", value: "Ventilé" },
    ],
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800"],
    categorie: "scolaire",
    famille: "arts",
    badge: "Rentrée",
  },
  {
    slug: "crayons-couleur-aquarellables-24",
    name: "Crayons de couleur aquarellables (lot de 24)",
    price: 25.90,
    tagline: "Un coup de pinceau et la couleur se fond",
    description:
      "Vingt-quatre crayons aquarellables à mine tendre 3,3 mm : on colorie à sec puis on estompe à l'eau pour un rendu aquarelle.",
    specs: [
      { label: "Contenu", value: "24 crayons" },
      { label: "Mine", value: "3,3 mm, aquarellable" },
      { label: "Usage", value: "Coloriage à sec ou à l'eau" },
    ],
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800"],
    categorie: "scolaire",
    famille: "arts",
    badge: "Rentrée",
  },
  {
    slug: "gouache-tubes-12-couleurs",
    name: "Gouache 12 tubes de couleurs",
    price: 20.90,
    tagline: "Couleurs franches, bonne couvrance",
    description:
      "Douze tubes de 12 ml de gouache extra-fine, couleurs vives et opaques, miscibles entre elles et nettoyables à l'eau.",
    specs: [
      { label: "Contenu", value: "12 tubes de 12 ml" },
      { label: "Type", value: "Gouache extra-fine" },
      { label: "Nettoyage", value: "À l'eau" },
    ],
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800"],
    categorie: "scolaire",
    famille: "arts",
    badge: "Rentrée",
  },
  {
    slug: "pinceaux-scolaires-lot-10",
    name: "Pinceaux scolaires (lot de 10)",
    price: 13.90,
    tagline: "Ronds et plats, du n°2 au n°12",
    description:
      "Assortiment de 10 pinceaux à virole aluminium sertie et manche verni : 5 ronds et 5 plats, du n°2 au n°12.",
    specs: [
      { label: "Contenu", value: "10 pinceaux" },
      { label: "Formes", value: "5 ronds, 5 plats" },
      { label: "Tailles", value: "N°2 à n°12" },
      { label: "Virole", value: "Aluminium sertie" },
    ],
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800"],
    categorie: "scolaire",
    famille: "arts",
    badge: "Rentrée",
  },
  {
    slug: "pastels-gras-lot-24",
    name: "Pastels gras (lot de 24)",
    price: 12.90,
    tagline: "Couleurs franches qui s'estompent au doigt",
    description:
      "Vingt-quatre pastels gras de 11 mm sous étui carton, couleurs mélangeables au doigt et adaptées au papier à dessin comme au papier de couleur.",
    specs: [
      { label: "Contenu", value: "24 pastels" },
      { label: "Diamètre", value: "11 mm" },
      { label: "Usage", value: "Papier à dessin et papier de couleur" },
    ],
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800"],
    categorie: "scolaire",
    famille: "arts",
    badge: "Rentrée",
  },
  {
    slug: "ardoise-blanche-effacable-a4",
    name: "Ardoise blanche effaçable A4",
    price: 13.90,
    tagline: "On écrit, on efface, on recommence",
    description:
      "Ardoise blanche A4 double face avec cadre de protection, livrée avec un marqueur et un effaceur feutre aimanté.",
    specs: [
      { label: "Format", value: "A4" },
      { label: "Faces", value: "2 faces effaçables" },
      { label: "Livré avec", value: "Marqueur et effaceur" },
    ],
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800"],
    categorie: "scolaire",
    famille: "arts",
    badge: "Rentrée",
  },
  {
    slug: "palette-godets-peinture",
    name: "Palette à godets 10 alvéoles",
    price: 8.90,
    tagline: "Dix couleurs sans mélange involontaire",
    description:
      "Palette en plastique blanc à 10 alvéoles profondes et zone de mélange centrale, lavable à l'eau et empilable.",
    specs: [
      { label: "Alvéoles", value: "10 + zone de mélange" },
      { label: "Matière", value: "Plastique lavable" },
      { label: "Empilable", value: "Oui" },
    ],
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800"],
    categorie: "scolaire",
    famille: "arts",
    badge: "Rentrée",
  },
  {
    slug: "tablier-peinture-enfant",
    name: "Tablier de peinture enfant",
    price: 17.90,
    tagline: "Les vêtements ressortent intacts",
    description:
      "Tablier à manches longues en nylon enduit imperméable, poignets élastiqués et fermeture arrière par scratch, avec grande poche ventrale.",
    specs: [
      { label: "Matière", value: "Nylon enduit imperméable" },
      { label: "Manches", value: "Longues, poignets élastiqués" },
      { label: "Fermeture", value: "Scratch au dos" },
      { label: "Entretien", value: "Lavable en machine 30°" },
    ],
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800"],
    categorie: "scolaire",
    famille: "arts",
    badge: "Rentrée",
  },
  {
    slug: "pate-a-modeler-lot-8",
    name: "Pâte à modeler (lot de 8 pots)",
    price: 13.90,
    tagline: "Elle ne sèche pas entre deux séances",
    description:
      "Huit pots de 100 g de pâte à modeler souple sans gluten, réutilisable et non toxique, conforme à la norme EN 71.",
    specs: [
      { label: "Contenu", value: "8 pots de 100 g" },
      { label: "Formule", value: "Sans gluten, non toxique" },
      { label: "Norme", value: "EN 71" },
    ],
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800"],
    categorie: "scolaire",
    famille: "arts",
    badge: "Rentrée",
  },
  {
    slug: "carnet-croquis-a4-100p",
    name: "Carnet de croquis A4 100 pages",
    price: 16.90,
    tagline: "Cent pages pour dessiner en continu",
    description:
      "Carnet de croquis A4 à reliure spirale, 100 pages de papier blanc 120 g au grain léger, couverture rigide.",
    specs: [
      { label: "Format", value: "A4" },
      { label: "Pages", value: "100" },
      { label: "Grammage", value: "120 g" },
      { label: "Reliure", value: "Spirale" },
    ],
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800"],
    categorie: "scolaire",
    famille: "arts",
    badge: "Rentrée",
  },
  {
    slug: "cartable-primaire-38cm",
    name: "Cartable primaire 38 cm",
    price: 53.90,
    tagline: "Dos rembourré, épaules soulagées",
    description:
      "Cartable de 38 cm à deux compartiments, dos matelassé et bretelles rembourrées réglables, fond renforcé et bandes réfléchissantes.",
    specs: [
      { label: "Taille", value: "38 cm" },
      { label: "Compartiments", value: "2 + poche frontale" },
      { label: "Dos", value: "Matelassé" },
      { label: "Sécurité", value: "Bandes réfléchissantes" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
  {
    slug: "sac-a-dos-college-30l",
    name: "Sac à dos collège 30 L",
    price: 60.90,
    tagline: "Trente litres et un compartiment ordinateur",
    description:
      "Sac à dos de 30 L à trois compartiments dont un rembourré pour ordinateur 15 pouces, dos aéré et bretelles ergonomiques.",
    specs: [
      { label: "Capacité", value: "30 L" },
      { label: "Compartiments", value: "3, dont un pour PC 15 pouces" },
      { label: "Dos", value: "Aéré, matelassé" },
      { label: "Poches latérales", value: "2, filet" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
  {
    slug: "trousse-simple-compartiment",
    name: "Trousse simple compartiment",
    price: 12.90,
    tagline: "L'essentiel, sans fioritures",
    description:
      "Trousse rectangulaire à un compartiment et fermeture éclair pleine longueur, tissu polyester résistant et doublure intérieure.",
    specs: [
      { label: "Compartiments", value: "1" },
      { label: "Fermeture", value: "Éclair pleine longueur" },
      { label: "Matière", value: "Polyester" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
  {
    slug: "trousse-double-compartiment",
    name: "Trousse double compartiment",
    price: 18.90,
    tagline: "Stylos d'un côté, matériel de l'autre",
    description:
      "Trousse à deux compartiments indépendants avec passants élastiques intérieurs, tissu résistant et double fermeture éclair.",
    specs: [
      { label: "Compartiments", value: "2 indépendants" },
      { label: "Rangement", value: "Passants élastiques" },
      { label: "Fermeture", value: "2 éclairs" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
  {
    slug: "plumier-garni-scolaire",
    name: "Plumier garni scolaire",
    price: 33.90,
    tagline: "La rentrée réglée en un achat",
    description:
      "Trousse garnie prête à l'emploi : stylos bille 4 couleurs, crayon, gomme, taille-crayon, règle, ciseaux, colle et 12 crayons de couleur.",
    specs: [
      { label: "Contenu", value: "Trousse + 20 pièces" },
      { label: "Inclus", value: "Stylos, crayon, gomme, règle, ciseaux, colle" },
      { label: "Coloriage", value: "12 crayons de couleur" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
  {
    slug: "sac-de-sport-40l",
    name: "Sac de sport 40 L",
    price: 40.90,
    tagline: "Le sac du jour d'EPS",
    description:
      "Sac de sport de 40 L avec compartiment chaussures séparé et ventilé, bandoulière rembourrée amovible et fond renforcé.",
    specs: [
      { label: "Capacité", value: "40 L" },
      { label: "Compartiment", value: "Chaussures séparé et ventilé" },
      { label: "Bandoulière", value: "Rembourrée, amovible" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
  {
    slug: "boite-a-gouter-compartiments",
    name: "Boîte à goûter à compartiments",
    price: 17.90,
    tagline: "Trois cases, aucun mélange",
    description:
      "Boîte à goûter à trois compartiments séparés et couvercle à joint étanche, sans BPA, passant au lave-vaisselle.",
    specs: [
      { label: "Compartiments", value: "3 séparés" },
      { label: "Étanchéité", value: "Joint silicone" },
      { label: "Matière", value: "Plastique sans BPA" },
      { label: "Entretien", value: "Lave-vaisselle" },
    ],
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
  {
    slug: "gourde-inox-750ml",
    name: "Gourde inox 750 ml",
    price: 31.90,
    tagline: "Trois quarts de litre, gardés au frais",
    description:
      "Gourde en inox double paroi de 750 ml, isolation sous vide conservant le froid 24 h et le chaud 12 h, bouchon vissé étanche.",
    specs: [
      { label: "Contenance", value: "750 ml" },
      { label: "Isolation", value: "24 h froid / 12 h chaud" },
      { label: "Matière", value: "Inox alimentaire sans BPA" },
      { label: "Bouchon", value: "Vissé, étanche" },
    ],
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
  {
    slug: "etiquettes-scolaires-lot-120",
    name: "Étiquettes scolaires à personnaliser (lot de 120)",
    price: 13.90,
    tagline: "Plus d'affaires perdues",
    description:
      "Cent vingt étiquettes autocollantes résistantes à l'eau, à écrire au marqueur permanent, pour marquer cahiers, trousses et gourdes.",
    specs: [
      { label: "Contenu", value: "120 étiquettes" },
      { label: "Résistance", value: "Eau et frottements" },
      { label: "Support", value: "Cahiers, trousses, gourdes, vêtements" },
    ],
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
  {
    slug: "casque-audio-filaire-scolaire",
    name: "Casque audio filaire scolaire",
    price: 33.90,
    tagline: "Volume limité, oreilles préservées",
    description:
      "Casque filaire jack 3,5 mm à volume limité à 85 dB, arceau réglable et coussinets souples, adapté aux séances de langues et au travail sur écran.",
    specs: [
      { label: "Connexion", value: "Jack 3,5 mm" },
      { label: "Volume", value: "Limité à 85 dB" },
      { label: "Arceau", value: "Réglable" },
      { label: "Coussinets", value: "Mousse souple" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
  {
    slug: "cle-usb-64go",
    name: "Clé USB 64 Go",
    price: 22.90,
    tagline: "Les exposés dans la poche",
    description:
      "Clé USB 3.2 de 64 Go à connecteur rétractable, compatible Windows, macOS et Linux sans installation.",
    specs: [
      { label: "Capacité", value: "64 Go" },
      { label: "Interface", value: "USB 3.2" },
      { label: "Connecteur", value: "Rétractable" },
      { label: "Compatibilité", value: "Windows, macOS, Linux" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
  {
    slug: "tapis-souris-antiderapant",
    name: "Tapis de souris antidérapant",
    price: 10.90,
    tagline: "La souris suit, le tapis reste",
    description:
      "Tapis de souris 26x21 cm à surface textile micro-tissée et base caoutchouc antidérapante, bords surpiqués qui ne s'effilochent pas.",
    specs: [
      { label: "Dimensions", value: "26 x 21 cm" },
      { label: "Surface", value: "Textile micro-tissé" },
      { label: "Base", value: "Caoutchouc antidérapant" },
      { label: "Bords", value: "Surpiqués" },
    ],
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800"],
    categorie: "scolaire",
    famille: "sacs",
    badge: "Rentrée",
  },
];
